$schema: https://json-schema.org/draft/2020-12/schema
description: >-
  The Generic Profile "Point cloud thinning" -- see generic-profiles.generic-profile for the general shape every Generic Profile shares.
allOf:
  - $ref: bblocks://generic-profiles.generic-profile
  - type: object
    properties:
      id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/point-cloud-thinning"}
      type: {const: GenericProfile}
      prefLabel: {const: "Point cloud thinning"}
  - type: object
    properties:
      metadata:
        allOf:
        - contains:
            type: object
            required: [role, href]
            properties:
              role: {const: 'http://www.opengis.net/spec/wps/2.0/def/process-profile/concept'}
              href: {const: 'https://geolabs.github.io/bblocks-generic-profiles/def/concept/point-cloud-processing'}
      inputs:
        properties:
          points: {required: [id, dataType], properties: {id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/point-cloud-thinning/inputs/points"}, dataType: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/data-type/point-cloud"}}}
          percentage: {required: [id, dataType], properties: {id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/point-cloud-thinning/inputs/percentage"}, dataType: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/data-type/number"}}}
      outputs:
        properties:
          result: {required: [id, dataType], properties: {id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/point-cloud-thinning/outputs/result"}, dataType: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/data-type/point-cloud"}}}
