$schema: https://json-schema.org/draft/2020-12/schema
description: >-
  The Generic Profile "Raster crop" -- see generic-profiles.generic-profile for the general
  shape every Generic Profile shares.
allOf:
  - $ref: bblocks://generic-profiles.generic-profile
  - type: object
    properties:
      id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/raster-crop"}
      type: {const: GenericProfile}
      prefLabel: {const: "Raster crop"}
  - type: object
    properties:
      metadata:
        allOf:
        - contains:
            type: object
            required: [role, href]
            properties:
              role: {const: 'http://www.opengis.net/spec/wps/2.0/def/process-profile/concept'}
              href: {const: 'https://geolabs.github.io/bblocks-generic-profiles/def/concept/raster-coverage-processing'}
      inputs:
        properties:
          raster: {required: [id, dataType], properties: {id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/raster-crop/inputs/raster"}, dataType: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/data-type/raster"}}}
          areaOfInterest: {required: [id, dataType], properties: {id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/raster-crop/inputs/areaOfInterest"}, dataType: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/data-type/bounding-box"}}}
      outputs:
        properties:
          raster: {required: [id, dataType], properties: {id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/raster-crop/outputs/raster"}, dataType: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/data-type/raster"}}}
