$schema: https://json-schema.org/draft/2020-12/schema
description: >-
  The Generic Profile "Unary spatial predicate" -- see generic-profiles.generic-profile for the general
  shape every Generic Profile shares.
allOf:
  - $ref: bblocks://generic-profiles.generic-profile
  - type: object
    properties:
      id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/unary-spatial-predicate"}
      type: {const: GenericProfile}
      prefLabel: {const: "Unary spatial predicate"}
