$schema: https://json-schema.org/draft/2020-12/schema
description: >-
  The Concept "Vector Geometry Processing" -- see generic-profiles.concept for the general shape
  every Concept shares.
allOf:
  - $ref: bblocks://generic-profiles.concept
  - type: object
    properties:
      id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/concept/vector-geometry-processing"}
      type: {const: Concept}
      prefLabel: {const: "Vector Geometry Processing"}
