$schema: https://json-schema.org/draft/2020-12/schema
description: >-
  The Generic Profile "Binary spatial set operation" -- see generic-profiles.generic-profile for the general
  shape every Generic Profile shares.
allOf:
  - $ref: bblocks://generic-profiles.generic-profile
  - type: object
    properties:
      id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/binary-spatial-operation"}
      type: {const: GenericProfile}
      prefLabel: {const: "Binary spatial set operation"}
  - type: object
    properties:
      metadata:
        allOf:
        - contains:
            type: object
            required: [role, href]
            properties:
              role: {const: 'http://www.opengis.net/spec/wps/2.0/def/process-profile/concept'}
              href: {const: 'https://geolabs.github.io/bblocks-generic-profiles/def/concept/vector-geometry-processing'}
      inputs:
        properties:
          geometry1: {required: [id], properties: {id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/binary-spatial-operation/inputs/geometry1"}}}
          geometry2: {required: [id], properties: {id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/binary-spatial-operation/inputs/geometry2"}}}
      outputs:
        properties:
          result: {required: [id], properties: {id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/binary-spatial-operation/outputs/result"}}}
