$schema: https://json-schema.org/draft/2020-12/schema
description: >-
  The Generic Profile "Radiometric index" -- see generic-profiles.generic-profile for the general
  shape every Generic Profile shares.
allOf:
  - $ref: bblocks://generic-profiles.generic-profile
  - type: object
    properties:
      id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/radiometric-index"}
      type: {const: GenericProfile}
      prefLabel: {const: "Radiometric index"}
  - type: object
    properties:
      metadata:
        allOf:
        - contains:
            type: object
            required: [role, href]
            properties:
              role: {const: 'http://www.opengis.net/spec/wps/2.0/def/process-profile/concept'}
              href: {const: 'https://geolabs.github.io/bblocks-generic-profiles/def/concept/raster-coverage-processing'}
      inputs:
        properties:
          rasters: {required: [id], properties: {id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/radiometric-index/inputs/rasters"}}}
          index: {required: [id], properties: {id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/radiometric-index/inputs/index"}}}
      outputs:
        properties:
          raster: {required: [id], properties: {id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/radiometric-index/outputs/raster"}}}
