$schema: https://json-schema.org/draft/2020-12/schema
description: >-
  The Generic Profile "Unary geometry operation" -- see generic-profiles.generic-profile for the general
  shape every Generic Profile shares.
allOf:
  - $ref: bblocks://generic-profiles.generic-profile
  - type: object
    properties:
      id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/unary-geometry-operation"}
      type: {const: GenericProfile}
      prefLabel: {const: "Unary geometry operation"}
  - type: object
    properties:
      metadata:
        allOf:
        - contains:
            type: object
            required: [role, href]
            properties:
              role: {const: 'http://www.opengis.net/spec/wps/2.0/def/process-profile/concept'}
              href: {const: 'https://geolabs.github.io/bblocks-generic-profiles/def/concept/vector-geometry-processing'}
      inputs:
        properties:
          geometry: {required: [id, dataType], properties: {id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/unary-geometry-operation/inputs/geometry"}, dataType: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/data-type/geometry"}}}
      outputs:
        properties:
          result: {required: [id, dataType], properties: {id: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/generic-profile/unary-geometry-operation/outputs/result"}, dataType: {const: "https://geolabs.github.io/bblocks-generic-profiles/def/data-type/geometry"}}}
